### ISSUE TITLE
Windows Binaries and other Chromium based browsers

### ISSUE THREAD

**Issue by c-sanchez** [kkocdko/crknob#2]
Hi, please upload Windows binaries to download.

Does it require a specific version of Chrome or can it work with any version?

Is it possible to use it with Chromium?
Maybe even Ungoogled Chromium?

**Comment by kkocdko** [comment]
Sorry for the later reply, my e-mail was filled with notifications.

1. Due to a ridiculous reason<sup>(1)</sup>, I determined not to provide binary.

2. It supports Chrome versions that use the current encrypt way. It worked from this repo published to now (`100.0.4896.60`) and may still work for a long time.

3. Chromium is supported of course, and there is a high probability that variants that are close to upstream will also be supported.

(1) One of my best friends open-source a webpage shell, and some anti-government activists used it to make their promotional app (they mentioned it in the confession), then my friend was arrested arbitrarily. So I decide to make a filter (yeah just not provide binary, you should build this at your hand). I want to protect myself in this terrible environment.

**Comment by c-sanchez** [comment]
Don't worry, I'm glad you answered me anyway.

Holy shit, unbelievable the stupid things that can get someone in trouble for :(
I really hope that your friend is out of that problem and is much better.

I don't really have the ability to compile almost anything, but I'll see if I can find something.

**Comment by kkocdko** [comment]
**[shuax/chrome_plus](https://github.com/shuax/chrome_plus/actions/runs/2084453154#:~:text=Size-,windows_x64,-122%20KB) may be what you want. Binary provided by GitHub Actions.**

`chrome_plus` is the new version of `GreenChrome` which I mentioned at `README.md`. I choose to create this simple patch because `GreenChrome` has many functions which I'm not using, and these functions caused many extra bugs after Chromium's update.
